{
 "title": "Überblick Meckauer Weg",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "agg_interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Ausfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  -count(direction) as \"IN\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time asc;"
    },
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"OUT\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Aktuelle Auslastung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "select \n  m.name as metric, \n  percentile_disc(0.95) within group(order by a.count) as value \nfrom areaoccupancy a\n  join metadata m on a.metadata_id = m.id\nwhere a.occupancy_time < $__timeTo()\n  and a.occupancy_time > $__timeTo()::timestamptz - interval '1m'\n  and m.name like 'parking%'\ngroup by metric;"
    }
   ]
  },
  {
   "title": "Behindertenparkplätze",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n  m.name as metric, \n  percentile_disc(0.8) within group(order by a.count) as value \nfrom areaoccupancy a\n  join metadata m on a.metadata_id = m.id\nwhere a.occupancy_time < $__timeTo()\n  and a.occupancy_time > $__timeTo()::timestamptz - interval '1m'\n  and m.name = 'disabled-space'\ngroup by metric;"
    }
   ]
  },
  {
   "title": "Zu-/Abfluss 60 Minuten",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "select time_bucket('1h', l.crossing_time) as time,\n  -count(direction) as \"value\",\n  '52.423971288898635' as \"latitude\",\n  '10.786832184714068' as longitude\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time desc\nlimit 1;"
    },
    {
     "rawSql": "select time_bucket('1h', l.crossing_time) as time,\n  count(direction) as \"value\",\n  '52.423971288898635' as \"latitude\",\n  '10.786832184714068' as longitude\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "LiveView",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "WITH LatestOccupancy AS (\n    SELECT \n        ao.metadata_id,\n        ao.occupancy_time,\n        ao.count,\n        ao.object_class_id,\n        ROW_NUMBER() OVER (PARTITION BY ao.metadata_id ORDER BY ao.occupancy_time DESC) AS rn\n    FROM \n        public.areaoccupancy ao\n)\nSELECT\n\t'52.42420091311126' as latitude,\n\t'10.787117954345003' as longitude,\n\tsum(lo.count) as value\nFROM \n    public.metadata m\nLEFT JOIN \n    LatestOccupancy lo\nON \n    m.id = lo.metadata_id\nWHERE \n    lo.rn = 1 AND\n\tm.name like 'parking-meckauer-ost%';"
    },
    {
     "rawSql": "WITH LatestOccupancy AS (\n    SELECT \n        ao.metadata_id,\n        ao.occupancy_time,\n        ao.count,\n        ao.object_class_id,\n        ROW_NUMBER() OVER (PARTITION BY ao.metadata_id ORDER BY ao.occupancy_time DESC) AS rn\n    FROM \n        public.areaoccupancy ao\n)\nSELECT\n\t'52.42438246867477' as latitude,\n\t'10.786820229161787' as longitude,\n\tsum(lo.count) as value\nFROM \n    public.metadata m\nLEFT JOIN \n    LatestOccupancy lo\nON \n    m.id = lo.metadata_id\nWHERE \n    lo.rn = 1 AND\n\tm.name like 'parking-meckauer-west%';"
    },
    {
     "rawSql": "WITH LatestOccupancy AS (\n    SELECT \n        ao.metadata_id,\n        ao.occupancy_time,\n        ao.count,\n        ao.object_class_id,\n        ROW_NUMBER() OVER (PARTITION BY ao.metadata_id ORDER BY ao.occupancy_time DESC) AS rn\n    FROM \n        public.areaoccupancy ao\n)\nSELECT\n\t'52.42438695221193' as latitude,\n\t'10.786989208315376' as longitude,\n\tsum(lo.count) as value\nFROM \n    public.metadata m\nLEFT JOIN \n    LatestOccupancy lo\nON \n    m.id = lo.metadata_id\nWHERE \n    lo.rn = 1 AND\n\tm.name like 'parking-meckauer-center%';"
    },
    {
     "rawSql": "WITH LatestOccupancy AS (\n    SELECT \n        ao.metadata_id,\n        ao.occupancy_time,\n        ao.count,\n        ao.object_class_id,\n        ROW_NUMBER() OVER (PARTITION BY ao.metadata_id ORDER BY ao.occupancy_time DESC) AS rn\n    FROM \n        public.areaoccupancy ao\n)\nSELECT\n\t'52.424037614491695' as latitude,\n\t'10.786740270497948' as longitude,\n\tsum(lo.count) as value\nFROM \n    public.metadata m\nLEFT JOIN \n    LatestOccupancy lo\nON \n    m.id = lo.metadata_id\nWHERE \n    lo.rn = 1 AND\n\tm.name like 'disabled%';"
    }
   ]
  },
  {
   "title": "Ausfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Einfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Zu-/Abfluss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc) as in  \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\norder by l.crossing_time asc;"
    },
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc) as out \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\norder by l.crossing_time asc;"
    }
   ]
  },
  {
   "title": "Einfahrt Heute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc)   \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in' and l.crossing_time > CURRENT_DATE\norder by l.crossing_time asc;"
    }
   ]
  },
  {
   "title": "Ausfahrt Heute",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc)   \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out' and l.crossing_time > CURRENT_DATE\norder by l.crossing_time asc;"
    }
   ]
  }
 ]
}