apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-init-scripts
  namespace: {{ .Values.namespace }} 
data:
  custom-config-01.sh: |-
    psql -d "$1" <<__SQL__
            create user analytics password '{{ .Values.passwords.analytics }}';
    __SQL__
  
  custom-config-02.sh: |-
    psql -d "$1" <<__SQL__
            create user observatory password '{{ .Values.passwords.observatory }}';
    __SQL__

  custom-config-03.sh: |-
    psql -d "$1" <<__SQL__
        SELECT 'CREATE DATABASE "analytics" owner analytics'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'analytics')\gexec
    __SQL__

  custom-config-04.sh: |-
    psql -d "$1" <<__SQL__
        SELECT 'CREATE DATABASE "observatory" owner observatory'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'observatory')\gexec
    __SQL__

  custom-config-05.sh: |-
    psql -d "$1" <<__SQL__
            create user observatory-config password '{{ .Values.passwords.observatoryconfig }}';
    __SQL__

  custom-config-06.sh: |-
    psql -d "$1" <<__SQL__
        SELECT 'CREATE DATABASE "observatory-config" owner observatory-config'
        WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'observatory-config')\gexec
    __SQL__