{
 "title": "Parksuchverkehr",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "suchflaechen",
    "query": "SELECT\n  name\nFROM\n  metadata\nWHERE \n  name like 'road%' AND classification = 'observe'"
   },
   {
    "name": "agg_interval",
    "label": "Aggregations Intervall",
    "query": "1m, 5m, 10m, 30m, 1h, 3h, 6h, 12h, 24h"
   }
  ]
 },
 "panels": [
  {
   "title": "Gesperrte Areale im Überblick",
   "type": "geomap",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.424500' as latitude,\n\t'10.78688' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'road-meckauer-west' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.424500' as latitude,\n\t'10.78715' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'road-meckauer-east' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Fahrzeuge in Areal $suchflaechen",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "repeat": "suchflaechen",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.42420091311126' as latitude,\n\t'10.787117954345003' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like $suchflaechen and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Parksuchverkehr",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "select \n  m.name as metric, \n  percentile_disc(0.9) within group(order by a.count) as value, \n  time_bucket_gapfill('$agg_interval', a.occupancy_time) as time \nfrom areaoccupancy a\n  join metadata m on a.metadata_id = m.id\nwhere $__timeFilter(a.occupancy_time)\n  and m.name like 'road%'\ngroup by time, metric \norder by time desc ;"
    }
   ]
  },
  {
   "title": "Flächen Parksuchverkehr",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  metadata\nWHERE \n  name like 'road%' AND classification = 'observe'\nLIMIT\n  50"
    }
   ]
  }
 ]
}