{
 "title": "Überblick Meckauer Weg",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agg_interval",
    "query": "10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Ausfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  -count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time asc;"
    },
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Aktuelle Auslastung",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select sum(s.average)\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'parking%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Behindertenparkplätze",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select sum(s.average)\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'disabled%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Zu-/Abfluss 60 Minuten",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "select time_bucket('1h', l.crossing_time) as time,\n  -count(direction) as \"value\",\n  '52.423971288898635' as \"latitude\",\n  '10.786832184714068' as longitude\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time desc\nlimit 1;"
    },
    {
     "rawSql": "select time_bucket('1h', l.crossing_time) as time,\n  -count(direction) as \"value\",\n  '52.423971288898635' as \"latitude\",\n  '10.786832184714068' as longitude\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time desc\nlimit 1;"
    }
   ]
  },
  {
   "title": "LiveView",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.42420091311126' as latitude,\n\t'10.787117954345003' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'parking-meckauer-ost%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.42438246867477' as latitude,\n\t'10.786820229161787' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'parking-meckauer-west%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.42438695221193' as latitude,\n\t'10.786989208315376' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'parking-meckauer-center%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.424037614491695' as latitude,\n\t'10.786740270497948' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'disabled%' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Ausfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Einfahrt",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "select time_bucket('$agg_interval', l.crossing_time) as time,\n  count(direction) as \"value\"\nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\ngroup by time\norder by time asc;"
    }
   ]
  },
  {
   "title": "Zu-/Abfluss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc) as in  \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in'\norder by l.crossing_time asc;"
    },
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc) as out \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out'\norder by l.crossing_time asc;"
    }
   ]
  },
  {
   "title": "Einfahrt 24 Stunden",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc)   \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'in' and l.crossing_time > CURRENT_DATE - 1\norder by l.crossing_time asc;"
    }
   ]
  },
  {
   "title": "Ausfahrt 24 Stunden",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select l.crossing_time as time,\n  count(direction) over (partition by m.name order by l.crossing_time asc)   \nfrom linecrossing l\n  join metadata m on l.metadata_id = m.id\nwhere m.name = 'flow-meckauer-main' and l.direction = 'out' and l.crossing_time > CURRENT_DATE - 1\norder by l.crossing_time asc;"
    }
   ]
  }
 ]
}