{
 "title": "Unbefugtes Halten & Parken",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "unbefugte_areale",
    "query": "SELECT\n  name\nFROM\n  metadata\nWHERE \n  name like 'restricted%' AND classification = 'observe'"
   }
  ]
 },
 "panels": [
  {
   "title": "Fahrzeuge in Areal $unbefugte_areale",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "repeat": "unbefugte_areale",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.42420091311126' as latitude,\n\t'10.787117954345003' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like $unbefugte_areale and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Gesperrte Areale im Überblick",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 10, "x": 4, "y": 0 },
   "targets": [
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.424100' as latitude,\n\t'10.7869' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'restricted-meckauer-bicycle01' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.424500' as latitude,\n\t'10.78715' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'restricted-meckauer-road01' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    },
    {
     "rawSql": "select \n    sum(s.average) as value,\n    '52.423950' as latitude,\n\t'10.7868' as longitude\nfrom (\n    select\n        percentile_disc(0.9) within group(order by a.count) as average,\n        m.name\n    from areaoccupancy a\n        join metadata m on a.metadata_id = m.id\n    where\n        m.name like 'restricted-meckauer-entry01' and\n        a.occupancy_time < $__timeTo() and\n        a.occupancy_time > $__timeTo()::timestamp - interval '30s'\n    group by m.name\n) s;"
    }
   ]
  },
  {
   "title": "Unbefugte Areale",
   "type": "table",
   "gridPos": { "h": 6, "w": 14, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM\n  metadata\nWHERE \n  name like 'restricted%' AND classification = 'observe'\nLIMIT\n  50"
    }
   ]
  }
 ]
}