repositories:
  - name: timescale
    url: https://charts.timescale.com/
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: starwit-internal
    url: https://helm.internal.starwit-infra.de
    username: chartmuseum
    password: {{ env "HELM_SECRET" }}
  - name: starwitorg
    url: registry-1.docker.io/starwitorg
    oci: true

helmDefaults:
  wait: true

environments:
  default:
    values:
      - namespace: smartparking-data
        hostname: markus-laptop
        tls: false
        auth:
          client_secret: smartparkingconfig
          realm_admin_pw: adminadmin
        dbpasswords: 
          databackend: {{ requiredEnv "DB_DATABACKEND_SECRET" }} 
          analytics: {{ requiredEnv "DB_ANALYTICS_SECRET" }}
          sae: {{ requiredEnv "DB_SAE_SECRET" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry
  wob-dev:
    values:  
      - namespace: smartparking-data
        hostname: wob-data.starwit-infra.de
        tls: true
        auth:
          client_secret: {{ requiredEnv "CLIENT_SECRET" }}
          keycloak_admin: {{ requiredEnv "KEYCLOAK_ADMIN" }}
          realm_admin_pw: adminadmin
        dbpasswords: 
          databackend: {{ requiredEnv "DB_DATABACKEND_SECRET" }} 
          analytics: {{ requiredEnv "DB_ANALYTICS_SECRET" }}
          sae: {{ requiredEnv "DB_SAE_SECRET" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry
  wob-staging:
    values:
      - namespace: smartparking-data
        hostname: staging.data-wolfsburg.de
        tls: true
        auth:
          client_secret: {{ requiredEnv "CLIENT_SECRET" }}
          keycloak_admin: {{ requiredEnv "KEYCLOAK_ADMIN" }}
          realm_admin_pw: adminadmin
        dbpasswords: 
          databackend: {{ requiredEnv "DB_DATABACKEND_SECRET" }} 
          analytics: {{ requiredEnv "DB_ANALYTICS_SECRET" }}
          sae: {{ requiredEnv "DB_SAE_SECRET" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry
  wob-prod:
    values:
      - namespace: smartparking-data
        hostname: data-wolfsburg.de
        tls: true
        auth:
          client_secret: {{ requiredEnv "CLIENT_SECRET" }}
          keycloak_admin: {{ requiredEnv "KEYCLOAK_ADMIN" }}
          realm_admin_pw: adminadmin
        dbpasswords: 
          databackend: {{ requiredEnv "DB_DATABACKEND_SECRET" }} 
          analytics: {{ requiredEnv "DB_ANALYTICS_SECRET" }}
          sae: {{ requiredEnv "DB_SAE_SECRET" }}
        pullSecret: {{ requiredEnv "PULL_SECRET" }} # Starwit's internal registry

---
releases:
  - name: config-data
    namespace: {{ .Values.namespace }}
    chart: ./config-data
    installed: true
    values:
      - config-data/values.gotmpl

  - name: keycloak
    namespace: {{ .Values.namespace }}
    chart: oci://registry-1.docker.io/bitnamicharts/keycloak
    version: "19.3.3"
    values:
      - httpRelativePath: / # set context path for keycloak console
        auth:
          adminUser: admin
          adminPassword: {{ .Values.auth.keycloak_admin }}
        proxy: edge
        extraStartupArgs: "--hostname-url=http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values.hostname }}"
        extraEnvVars:
          - name: KC_HOSTNAME_ADMIN_URL
            value: http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values | get "hostname" "localhost" }}            
        ingress:
          enabled: true
          autoGenerated: false
          hostname: auth.{{ .Values | get "hostname" "localhost" }}
        postgresql:
          nameOverride: "keycloak-postgresql"
          auth:
            password: bn_keycloak
        keycloakConfigCli:
          enabled: true
          existingConfigmap: smartparking

  - name: timescaledb
    namespace: {{ .Values.namespace }}
    chart: timescale/timescaledb-single
    version: 0.33.1  
    values:
      - replicaCount: 1
        service:
          primary:
            nodePort: 30001
            type: NodePort      
        postInit:
          - configMap:
              name: custom-init-scripts
              optional: true

  - name: grafana
    namespace: {{ .Values.namespace }}
    chart: grafana/grafana
    version: 7.3.7  
    values:
      - ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - dashboard.{{ .Values | get "hostname" "localhost" }}
          path: /
          tls:
          - hosts:
            - dashboard.{{ .Values | get "hostname" "localhost" }}
            secretName: dashboard.{{ .Values | get "hostname" "localhost" }}

        persistence:
          enabled: true
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Analytics-DB
                type: postgres
                editable: true
                url: timescaledb.{{ .Values.namespace }}.svc.cluster.local:5432
                user: analytics
                database: analytics
                secureJsonData:
                  password: '{{ .Values.dbpasswords.analytics }}'
        assertNoLeakedSecrets: false
        grafana.ini:
          server:
            root_url: http{{- if .Values.tls }}s{{- end }}://dashboard.{{ .Values | get "hostname" "localhost" }}/
          auth.generic_oauth:
            enabled: true
            name: Keycloak
            allow_sign_up: true
            scopes: openid profile email
            client_id: smartparkingconfig
            client_secret: {{ .Values.auth.client_secret }}
            auth_url: 'http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values | get "hostname" "localhost" }}/realms/smartparkingconfig/protocol/openid-connect/auth'
            token_url: 'http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values | get "hostname" "localhost" }}/realms/smartparkingconfig/protocol/openid-connect/token'
            api_url: 'http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values | get "hostname" "localhost" }}/realms/smartparkingconfig/protocol/openid-connect/userinfo'
            role_attribute_path: contains(roles[*], 'admin') && 'Admin' || contains(roles[*], 'dev') && 'Editor' || 'Viewer'
            allow_assign_grafana_admin: true

  - name: smartparkingconfig
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwit-internal/smartparkingconfig
    version: 0.5.0
    values:
      - image:
          tag: 0.5.0
        pullSecret:
          user: "docker"
          password: {{ .Values.pullSecret }}
        auth:
          enabled: true
          keycloak_url: http{{- if .Values.tls }}s{{- end }}://auth.{{ .Values.hostname }}/realms/smartparkingconfig
          client_id: smartparkingconfig
          client_secret: {{ .Values.auth.client_secret }}
        postgresql:
          auth:
            database: smartparkingconfig
            username: smartparkingconfig
            password: smartparkingconfig
        extraEnv: |
          - name: DATABACKEND_URL
            value: http://databackend-databackend-chart.{{ .Values.namespace }}.svc.cluster.local/databackend
          - name: DATABACKEND_CAMERAID
            value: Bahnhofstr12
          
        ingress:
          enabled: true
          hosts:
            - host: spc.{{ .Values.hostname }}
              paths:
                - path: /
                  pathType: ImplementationSpecific

  - name: databackend
    installed: true
    namespace: {{ .Values.namespace }}
    chart: starwitorg/databackend-chart
    version: 0.5.0
    values:
      - image:
          tag: 0.5.0
        extraEnv: |
          - name: SERVER_PORT
            value: "8081"
        databases:
          databackend: 
            internal: false
            host: timescaledb.{{ .Values.namespace }}.svc.cluster.local
            port: 5432          
            database: databackend
            username: databackend
            password: {{ .Values.dbpasswords.databackend }}
          sae:
            host: 100.90.178.96
            port: 30001
            database: sae
            username: sae
            password: {{ .Values.dbpasswords.sae }}
            detectionTableName: detection
          analytics:
            host: timescaledb.{{ .Values.namespace }}.svc.cluster.local
            port: 5432
            database: analytics
            username: analytics
            password: {{ .Values.dbpasswords.analytics }}
        postgresql:
          auth:
            database: databackend
            username: databackend
            password: {{ .Values.dbpasswords.databackend }}